// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// dotenv's default config() only loads .env, but this project only has
// .env.local (the Next.js convention for local secrets, already gitignored)
// — without pointing at it explicitly, these vars are undefined here even
// though the app itself reads it fine via Next.js's own env loading.
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

config({ path: ".env.local" });

// The CLI (migrate/db pull/studio/…) always connects directly to Postgres
// (DIRECT_URL, port 5432) — Supabase's pooled connection (DATABASE_URL,
// pgbouncer in transaction mode) doesn't support the advisory locks and
// session state migrations need, and hangs/fails if used here. The app's
// own runtime queries go through the pooled connection instead, via
// lib/db.ts's driver adapter — this config file has no effect on that.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Prisma 7 moved seed config here from package.json's old
    // `"prisma": { "seed": ... }` block.
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
